### ISSUE TITLE
Issues accessing bootcss.com

### ISSUE THREAD

**Issue by swt30** [piever/InteractBase.jl#104]
I tried installing and running this at work but it fails at the build step with `Failed to connect to cdn.bootcss.com port 443: Operation timed out`. Upon investigation it turns out this is because bootcss.com is hosted in China and the office firewall blocks connections to Chinese websites.

This surprised me—isn't bootstrap hosted at maxcdn.bootstrapcdn.com? What is bootcss.com and why is it in China?

**Comment by piever** [comment]
Should have chosen where to download things from. I think in the guide I was following, that was the link that was recommended to download the dependency (it's a js library for fancy sliders). Would the following links work for you?

https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/11.1.0/nouislider.min.js
https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/11.1.0/nouislider.min.css

**Comment by swt30** [comment]
They do work. Looks like bootcss.com is a Chinese-based CDN for a bunch of web libraries, which I imagine would be useful for doing web development from within the Great Firewall. I can download those libraries manually for now but it seems like it might be useful for the build script to have a couple of download location options for each dependency.

**Comment by piever** [comment]
cdnjs links also seem to work from China (tested [here](https://www.comparitech.com/privacy-security-tools/blockedinchina/?site_url=cdnjs.com)) so I'll just change the download to point there I guess.

**Comment by swt30** [comment]
Thanks @piever !
