### ISSUE TITLE
Feature request: array or non-linear slider range.

### ISSUE THREAD

**Issue by korsbo** [piever/InteractBase.jl#13]
Hi,

In Interact.jl, I would often use something like `selection_slider(logspace(-2,2,100))` to create appropriate ranges of values for my sliders. Could we implement that here too?

**Comment by korsbo** [comment]
I know that one can already do something like 

```julia
s = slider(-2:0.1:2)
map(x->10. ^x, observe(s))
```

and that works ok for me now, but if we get some value-labels (that would be nice) on the sliders then this will lead to a mismatch between the label and the value used.

**Comment by piever** [comment]
So, to make sure I understand, the feature requrest is:
- display the value of the slider on the right (something like [this](https://wikiki.github.io/form/slider/#javascript) for example) or on top of the "slider thumb" (which would you prefer?)
- if you pass an `AbstractArray` that's not a `linspace`, displayed value (as well as `observe(slider)`) should follow the values of the abstractarray, but the "slider thumb" moves linearly

This should actually be pretty straightforward to implement, the only constraint (for the HTML5 slider) is that the "visual steps" that the slider does when you drag it around are constant.

To add the value on the right of the slider, you would simply do:

```
s = slider(-2:0.1:2)
expval = map(x->10. ^x, observe(s))
hbox(s, expval)
```

but I can change the package so that this is done automatically when needed.

**Comment by korsbo** [comment]
> ```julia
> s = slider(-2:0.1:2)
> expval = map(x->10. ^x, observe(s))
> hbox(s, expval)
> ```

That's a neat solution, I did not think of that. 

But I still think that it may be useful for the sliders to accept arrays. The `slider([0.; logspace(-2,2,100)])` function would for example be useful.

**Comment by korsbo** [comment]
> display the value of the slider on the right (something like this for example) or on top of the "slider thumb" (which would you prefer?)

I don't have any initial preference. Would the slider-thumb option take up less space in the UI?

> if you pass an AbstractArray that's not a linspace, displayed value (as well as observe(slider)) should follow the values of the abstractarray, but the "slider thumb" moves linearly

yeah, let the slider move linearly, but the values adjust according to whatever was inputted.

**Comment by korsbo** [comment]
I tried out the value, slider side-by-side solution and found that the width of the slider behaves unexpectedly for this:

```julia
vbox(
        hbox(s, map(x->10. .^ x,  observe(s))), 
        s, map(x->10. .^ x,  observe(s))
    )
```

![interactbase_issue2](https://user-images.githubusercontent.com/16306680/40487311-ababb0da-5f5b-11e8-958c-a228fd831068.png)

Making the slider share horizontal space makes it shorter than it has to be.

**Comment by piever** [comment]
Unfortunately I'm afraid that's a "feature" of how `hbox` works. The slider defaults to being `is-fullwidth` and when it has an item to its right, it shrinks. You'd need to manually set its width (which you can do adding inline CSS to the slider) either to an absolute value or to a fraction of the viewport, for example:

```
s = slider(-2:0.1:2, style = "width:60vw;") # set slider to 60% of viewport, in this case the plot pane
vbox(
        hbox(s, map(x->10. .^ x,  observe(s))), 
        s, map(x->10. .^ x,  observe(s))
    )
```
or 
```
s = slider(-2:0.1:2, style = "width:300px;")
vbox(
        hbox(s, map(x->10. .^ x,  observe(s))), 
        s, map(x->10. .^ x,  observe(s))
    )
```

Happy to take suggestions on how to make this more user-friendly!

**Comment by korsbo** [comment]
I like the ability to specify the with. Now that you have told me about it, it's fairly easy. For increased user-friendliness, there could be some more Julia-like kwarg.

```julia
slider(-2:0.1:2, width=0.7)
```
for fractional width and something like 
```julia
using Measures
slider(-2:0.1:2, width=200px)
```
for absolute width.

**Comment by piever** [comment]
On latest master of InteractBulma I've fixed the layout of the slider and show the value on the right. Will add the option to have a "logarithmic slider" tomorrow.

**Comment by piever** [comment]
Should be working. If you want to test, you need to be on latest master of both InteractBulma and InteractBase. Then the following should work:

```julia
slider(vcat(0, logspace(-2, 2)), label = "Log slider")
```

**Comment by piever** [comment]
Now non linear slider works and in pure javascript (meaning no callback to a Julia function is required where moving the slider)
