### ISSUE TITLE
API consistency review

### ISSUE THREAD

**Issue by piever** [piever/InteractBase.jl#21]
This is an issue to decide the InteractBase API. The current approach tries to be as compatible as possible with the Interact.jl API which in turn is not fully consistent.

In Interact.jl, almost all arguments can be used as keyword arguments and a "positional" version is provided, that can take  as positional version the most "commonly used" keyword argument. It generally is `value`, but sometimes is `placeholder` and other times it's `label`. Still, there is some logic: the positional argument is `placeholder` for text input, `value` for "type input" (meaning input of non text types, like `Bool`, `Date`, `Color`,..) and `label` for buttons. [Here](https://piever.github.io/InteractBase.jl/latest/api_reference.html) is the current API reference.

One alternative would be as follows: 

- positional arguments are: arguments that define what values are allowed (meaning either `options` or `range` for a slider) and `value`
- everything else is a keyword argument, following the HTML5 name (`placeholder`, `label`, `multiple`, etc...)

The "fly in the ointment" of this rewrite is `button` as the HTML5 version of `button` takes argument that are not "keyword" and are the content of the button (generally `label` and `icon`).  In this case I see as sensible both signatures:

- `button(args...; value=0, kwargs...)` where `args` would be the button content (icon and label)
- `button(value = 0, label = "press me", icon = nothing, kwargs....)`

What is the consensus? Is it preferred to:

1. Keep as is
2. Go for the new design

And, in case of 2), what should the signature of `button` be?

cc: @shashi, @jobjob

**Comment by piever** [comment]
After some clean up of the current system, I'm not sure anymore that a rewrite of the API is necessary and the current version seems mostly consistent and "intuitive shorthands" always work (meaning `checkbox(true)`, textbox("Write here")`, `button("Click here!")`, etc..). The "fully consistent" version sketched above would definitely be more verbose.

**Comment by DarioSarra** [comment]
Generally speaking I find that the "positional" version of function arguments, despite requiring some memorisation, it's much easier to integrate in scripts were labels or other features want to be defined by variables. My guess is that the less verbose this variable assignment is the easier the overall GUI design is.

**Comment by shashi** [comment]
I think button label should also be kwarg, since that's consistent with everything else (except html5, but we can assume the user doesn't care about html5)...

I see @dariosarra's point. It could be useful to allow both positional and kwarg in many cases.

**Comment by piever** [comment]
I think it's a fair point: there will probably be a large fraction of users that don't know/care about html5, are not too keen on reading the docs and do not remember the correct keywords. I think with multiple dispatch it's quite easy to get most sensible signatures to work as intended (which is already almost the case, except for `button` and `checkbox`), I'll probably do that. The only important thing is, for every widget, to keep one signature as "canonical", so that it can be overloaded from InteractBulma & co.

**Comment by rdeits** [comment]
Personally, I have no attachment to the old Interact.jl API (I've rarely used anything more than `@manipulate`), so I'd favor whatever you think is the most self-consistent API going forward. But it sounds like the current API is already pretty good, so I'd certainly be happy to keep it.

**Comment by piever** [comment]
Closing as the new syntax is now in a released version.
