### ISSUE TITLE
Unitful support

### ISSUE THREAD

**Issue by rafaqz** [piever/InteractBase.jl#29]
It would be great if widgets supported Unitful.jl, so e.g. sliders can be time values. It might be in an addon package, but this issue is just a reminder to think about that when designing types and methods.

**Comment by piever** [comment]
For efficiency is much better if this display happens directly in javascript, so I would prefer to keep the underlying type javascript friendly. I'm not familiar with the Unitful package, is there a standard way to convert a "Unitful" value into a `Float64` plus a string defining the unit of measure?

**Comment by rafaqz** [comment]
Absolutely, its just a matter of splitting it into a number and label at some point. 

You won't want to depend on Unitful, so maybe a function that returns a number and label  and dispatches on the type of Number would be best. Then a glue package can actually depend on Unitful or whatever other unusual number types people might use.

**Comment by piever** [comment]
I'm doing a slider overhaul to implement sliders with multiple handles. As a side effect, this should get fixed and sliders should now accept any sorted arrays of things that can be printed with `showcompact` (I've tested kilograms and dates so far). It's still experimental, but if you:

```julia
Pkg.checkout("InteractBase")
Pkg.build("InteractBase")
```

you can try it with:

```julia
using InteractBase, Unitful
InteractBase.rangeslider(linspace(1u"kg", 10u"kg", 50), value = [3u"kg", 9u"kg"])) # pass an array to have several handles
```

I'm happy to have feedback on this one as it should eventually replace the original version.

**Comment by piever** [comment]
My plan was to replace `slider` with `rangeslider` eventually (already now, if you pass only one value to `rangeslider` it works as a regular slider, so that I don't have to maintain two versions. What's the consensus? Are there any advantages of the current `slider` implementation or can one simply use the other for your usecases?

**Comment by barche** [comment]
For me this is fine, my use case is the `@manipulate` macro in a notebook, so if it switches to a `rangeslider` in the background I don't mind at all.

**Comment by piever** [comment]
I see, before that happens you can do it by hand, meaning 
```julia
@manipulate for i in rangeslider(1m:1m:10m, label = "i")
...
end
```

**Comment by piever** [comment]
Closing as on master both sliders work with unitful quanities (and arrays of dates). Anything that can be sorted and printed as as string should work now.
