### ISSUE TITLE
Naming nit-picks

### ISSUE THREAD

**Issue by shashi** [piever/InteractBase.jl#3]
This package is very cool!

I have some minor naming suggestions:

1. `CSSFramework` -> something like `WidgetTheme` ? Because things like Material are not just CSS frameworks, they require some JS etc.
2. `setbackend` -> `settheme!` -- daisy chains nicely with the "theme" above.
3. The package itself maybe better as `InteractBase` -- let's makes Interact.jl depend on this and have a sensible default theme. InteractNext would become MaterialTheme.jl maybe, and then BulmaTheme.jl etc.

**Comment by piever** [comment]
That's a good point the default should be already with some nice style, I'll see if I can quickly choose on one which should be the one to also be used on Sputnik so it gets some testing.
