### ISSUE TITLE
widgets missing from documentation

### ISSUE THREAD

**Issue by DarioSarra** [piever/InteractBase.jl#39]
I ordered them as they appear on the export lists

datepicker, timepicker, colorpicker, spinbox
input, textarea, togglecontent
tabs, checkboxes, toggles, tabulator

cheers

**Comment by piever** [comment]
Seems like I'm only missing `tabs`, `tabulator` and `togglecontent` from [here](https://piever.github.io/InteractBase.jl/latest/api_reference.html), but maybe things are a bit hard to find. I should probably add a list of all widgets (without docstrings) that when clicked redirect to the docstring (pretty much like [here](http://juliadb.org/latest/api/)).
