### ISSUE TITLE
Use stack for themes?

### ISSUE THREAD

**Issue by shashi** [piever/InteractBase.jl#4]
Ref is simple, but not good for modularity.

If in my package I have a strong preference of using Material design, then I'm going to do `setbackend(Material())`.

But once you use something from my package anything you do next will also be of Material theme!!

To bypass this I'd have to do something like, first reach into `backend[]` ref, save the current value, do setbackend, then setbackend with the saved value to leave it in a previous state.

If we used stacks, I could use a `push!` and `pop!`, and in the middle call some other package which may change the theme too.

**Comment by piever** [comment]
I se, that's probably a good idea. Also, `slap_design!` could always call `libraries(backend)`, to automatically load the correct things without overwriting another global variable.
