### ISSUE TITLE
clarify use of `outer` and `postprocess`

### ISSUE THREAD

**Issue by piever** [piever/InteractBase.jl#9]

**Comment by shashi** [comment]
I left a comment about this here: https://github.com/piever/InteractBase.jl/commit/981c4f32607e3e7383da45ef0cc7bf9a242271e6#r29163874

**Comment by piever** [comment]
Had not idea the solution you proposed was possible, that's extremely helpful. Ideally then I'll try to ditch `postprocess` and replace it with the technique you propose. I still like to keep `outer` as it can be useful to give a custom container (horizontal versus vertical or adding some specific class).

**Comment by shashi** [comment]
> I still like to keep outer as it can be useful to give a custom container ...
> horizontal versus vertical or adding some specific class

why wouldn't vbox / hbox work? I see the point about being able to style after the fact. I think we should allow users to style `Scope`s directly, but modify the internal `.dom` object instead.

**Comment by piever** [comment]
Agreed: it seems using `outer` ends up being quite useful but I could take the habit of replacing it with the html object it aims to replace (instead of `outer = dom"div.field"` for example I could use `div_field =dom"div.field"` and specify in the docs that it is aimed at css backend developers, while in the docs I would only describe "public keywords".
